/*
SQLyog Ultimate v11.11 (64 bit)
MySQL - 5.5.5-10.4.24-MariaDB : Database - credifarma
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`credifarma` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;

USE `credifarma`;

/*Table structure for table `categories` */

DROP TABLE IF EXISTS `categories`;

CREATE TABLE `categories` (
  `id_category` int(11) NOT NULL AUTO_INCREMENT,
  `code_category` varchar(250) DEFAULT NULL,
  `name_category` varchar(250) DEFAULT NULL,
  `group_category` varchar(250) DEFAULT NULL,
  `pcreg_category` varchar(250) DEFAULT NULL,
  `usreg_category` varchar(250) DEFAULT NULL,
  `pcmod_category` varchar(250) DEFAULT NULL,
  `usmod_category` varchar(250) DEFAULT NULL,
  `date_created_category` date DEFAULT NULL,
  `date_updated_category` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id_category`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4;

/*Data for the table `categories` */

insert  into `categories`(`id_category`,`code_category`,`name_category`,`group_category`,`pcreg_category`,`usreg_category`,`pcmod_category`,`usmod_category`,`date_created_category`,`date_updated_category`) values (13,'A','Farmacos','M','Joel-PC','jmedrano','Joel-PC','jmedrano','2022-10-29','2022-10-29 10:10:36');

/*Table structure for table `companies` */

DROP TABLE IF EXISTS `companies`;

CREATE TABLE `companies` (
  `id_company` int(11) NOT NULL AUTO_INCREMENT,
  `ruc_company` varchar(250) DEFAULT NULL,
  `name_company` varchar(250) DEFAULT NULL,
  `address_company` varchar(250) DEFAULT NULL,
  `city_company` varchar(250) DEFAULT NULL,
  `phone_company` varchar(250) DEFAULT NULL,
  `date_created_company` date DEFAULT NULL,
  `date_updated_company` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id_company`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

/*Data for the table `companies` */

insert  into `companies`(`id_company`,`ruc_company`,`name_company`,`address_company`,`city_company`,`phone_company`,`date_created_company`,`date_updated_company`) values (1,'10472810371','JOEL VLADIMIR MEDRANO GUERE','GREGORIO SISA 133','CARABAYLLO','982009013','2022-10-26','2022-10-26 22:11:19'),(2,'10743183440','CARLOS ENRIQUE MEDRANO GUERE','AV. HUANDOY 7509','LOS OLIVOS','983263762','2022-10-26','2022-10-26 22:11:27'),(3,'10474909102','TIFFANY THALIA CUNZA CASRILLO','MERURIO ALTO','LOS OLIVOS',NULL,'2022-10-26','2022-10-26 22:11:02');

/*Table structure for table `laboratories` */

DROP TABLE IF EXISTS `laboratories`;

CREATE TABLE `laboratories` (
  `id_laboratory` int(11) NOT NULL AUTO_INCREMENT,
  `code_laboratory` varchar(250) DEFAULT NULL,
  `ruc_laboratory` varchar(250) DEFAULT NULL,
  `bussiness_name_laboratory` varchar(250) DEFAULT NULL,
  `name_laboratory` varchar(250) DEFAULT NULL,
  `address_laboratory` varchar(250) DEFAULT NULL,
  `postal_code_laboratory` varchar(250) DEFAULT NULL,
  `phone1_laboratory` varchar(250) DEFAULT NULL,
  `phone2_laboratory` varchar(250) DEFAULT NULL,
  `fax_laboratory` varchar(250) DEFAULT NULL,
  `email_laboratory` varchar(250) DEFAULT NULL,
  `ceo_laboratory` varchar(250) DEFAULT NULL,
  `contact_laboratory` varchar(250) DEFAULT NULL,
  `state_laboratory` int(11) DEFAULT 1,
  `pcreg_laboratory` varchar(250) DEFAULT NULL,
  `usreg_laboratory` varchar(250) DEFAULT NULL,
  `pcmod_laboratory` varchar(250) DEFAULT NULL,
  `usmod_laboratory` varchar(250) DEFAULT NULL,
  `date_created_laboratory` date DEFAULT NULL,
  `date_updated_laboratory` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id_laboratory`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4;

/*Data for the table `laboratories` */

insert  into `laboratories`(`id_laboratory`,`code_laboratory`,`ruc_laboratory`,`bussiness_name_laboratory`,`name_laboratory`,`address_laboratory`,`postal_code_laboratory`,`phone1_laboratory`,`phone2_laboratory`,`fax_laboratory`,`email_laboratory`,`ceo_laboratory`,`contact_laboratory`,`state_laboratory`,`pcreg_laboratory`,`usreg_laboratory`,`pcmod_laboratory`,`usmod_laboratory`,`date_created_laboratory`,`date_updated_laboratory`) values (3,'0001',NULL,'DROG LABORATORIO FARVET SAC','FARVET','VICTORIANO CASTILLO 141 URB. LOS JAZMINES MIRAFLOR',NULL,'2730979',NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,'2022-10-29','2022-10-29 21:59:21'),(5,'0002','10472810371','MEDRANO GÜERE JOEL VLADIMIR','SANTOLEE','CAL. GREGORIO SISA NRO. 133 URB. TUNGASUCA 2DA. ETAPA LIMA - LIMA - CARABAYLLO','150106','','',NULL,'','',NULL,1,'Joel-PC','jmedrano','Joel-PC','jmedrano','2022-10-29','2022-10-30 01:41:15'),(6,'0003','20492544745','CODEFAR S.A.C.','CODEFAR','JR. MATEO AGUILAR NRO. 220 INT. 401 URB. INGENIERIA LIMA - LIMA - SAN MARTIN DE PORRES','150135','','',NULL,'','',NULL,1,'Joel-PC','jmedrano','Joel-PC','jmedrano','2022-10-29','2022-10-30 01:40:47');

/*Table structure for table `substances` */

DROP TABLE IF EXISTS `substances`;

CREATE TABLE `substances` (
  `id_substance` int(11) NOT NULL AUTO_INCREMENT,
  `code_substance` varchar(250) DEFAULT NULL,
  `name_substance` varchar(250) DEFAULT NULL,
  `vadecum_substance` text DEFAULT NULL,
  `vadecumb_substance` text DEFAULT NULL,
  `state_substance` int(11) DEFAULT 1,
  `pcreg_substance` varchar(250) DEFAULT NULL,
  `usreg_substance` varchar(250) DEFAULT NULL,
  `pcmod_substance` varchar(250) DEFAULT NULL,
  `usmod_substance` varchar(250) DEFAULT NULL,
  `date_created_substance` date DEFAULT NULL,
  `date_updated_substance` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id_substance`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4;

/*Data for the table `substances` */

insert  into `substances`(`id_substance`,`code_substance`,`name_substance`,`vadecum_substance`,`vadecumb_substance`,`state_substance`,`pcreg_substance`,`usreg_substance`,`pcmod_substance`,`usmod_substance`,`date_created_substance`,`date_updated_substance`) values (5,'0001','ACICLOVIR 3% UNG','DESCRIPCION\r\n\r\nEL ACICLOVIR ES EL PRIMER NUCLÓSIDO PURÍNICO SINTÉTICO CON UNA ACTIVIDAD IN VITRO E IN VIVO INHIBITORIA DE LOS VIRUS HERPES HUMANOS INCLENYENDO EL VIRUS HERPES SIMPLE TIPOS 1 (HSV-1) Y 2 (HSV-2), VIRUS ZOSTER DE LA VARICELA (VZV), VIRUS DE EPSTEIN-BARR (EBV) Y CITOMEGALOVIRUS (CMV). LOS LOS CULTIVOS DE CÉLULAS, EL ACICLOVIR MUESTRA LA MAYOR ACTIVIDAD FRENTE AL HSV-1, SEGUIDOS DEL T HSV-2, VZV, EBV Y CMV.\r\n\r\nMECANISMO DE ACCION: LA ACCIÓN INHIBITORIA DEL ACICLOVIR ES MUY SELECTIVA PARALOS HSV-1, HSV-2, VZV Y EBV. LA ENZIMA IMIDINA KINASA (TK) DE LAS CÉLULAS NORMALES NO INFECTADAS NO ES SUSTRATO PARA EL ACICLOVIR. SIN EMBARTGO, LA ENZIMA CODIFICADA OPOR LOS VIRUS SENSIBLES CONVIERTE EL ACICLOVIR EN UN NUCLEÓTIDO ANÁLOGO EL ACIVLOBVIR MONOFOSFATO. ESTE MONOFOSFATO ES POSTERIORMENTE CONVERTIDO EN DIFOSFATO POR UNA GUANILATO KINASA Y A TRIFOSFATO POR OTRAS ENZIMAS. EL ACICLOVIR TRIFOSFATO INTERFIERE CON LA ADN-POLIMERASAS DE LOS VIRUS INHIBIENDO SU REPLICACIÓN.\r\n\r\nAUNQUE EL ACICLOVIR TRIFOSFATO TAMBIÉN INHIBE LA A-ADN POLIMERASA CELULAR, LO HACE EN MENOR GRADO QUE EN EL CASO DE LA POLIMERASA VIRAL. IN VITRO, EL ACICLOVIR TRIFOSFATO SE INCORPORA A CADENAS DE ADN EN CRECIMIENTO MEDIANTE LA ADN-POLIMERASA VIRAL Y EN MENOR GRADO POR LA A-ADN POLIMERASA CELULAR. CUANDO ESTO OCURRE, LA CADENA DE ADN QUEDA INTERRUMPIDA.\r\n\r\nEL ACICLOVIR ES CONVERTIDO A ACICLOVIR FOSFATO POR LAS CÉLULAS INFECTADAS POR VIRUS, DE TAL FORMA QUE EL FÁRMACO EN MUCHO MENOS TÓXICOS PARA LAS CÉLULAS NORMALES\r\n\r\nEL MODO DE FOSFORILIZACIÓN DEL ACICLOVIR EN LAS CÉLULAS INFECTADAS POR CITOMEGALOVIRUS NO ES BIEN CONOCIDO, SI BIEN PUEDEN IMPLICAR KINASAS CELULARES ACTIVADAS POR LOS VIRUS O UNA ENZIMA VIRAL NO IDENTIFICADA. EL ACICLOVIR NO ES ACTIVADO DEMASIADO EFICIENTEMENTE EN LAS CÉLULAS INFECTADAS POR CITOMEGALOVIRUS, LO QUE PUE EXPLICAR SU REDUCIDAD ACTIVIDAD IN VITRO.\r\n\r\nNO SE HA DETERMINADO LA RELACIÓN CUANTITATIVA ENTRE LA SUSCEPTIBILIDAD DEL ACICLOVIR IN VITRO Y LA RESPUESTA CLÍNICA EN EL HOMBRE. LOS RESULTADOS DE LOS TESTS DE SENSIBIOIDAD, EXPRESADOS COMO CONCENTRACIÓN DEL FÁRMACO REQUERIDA PARA INHIBIR EN UN 50% EL CRECIMIENTO DE LOS VIRUS EN UN CULTIVO CELULAR (ID50) VARÍAN MUCHO DEPENDIENDO DEL ENSAYO REALIZADO. ASÍ, LA ID50 DEL ACICLOVIR FRENTE A VIRUS HSV-1 PUEDE OSCILAR ENTRE 0.02 MG/ML (REDUCCIÓN DE LA PLACA EN CELULAS VERO) Y 5.9-13.5 MG/ML (REDUCCIÓN DE LA PLACA EN CÉLULAS DE RIÑÓN DE MONO. UTILIZANDO UN MÉTODO DE CAPTACIÓN DE COLORANTE EN CÉLULAS VERO, MÉTODO QUE SUMINISTRA UNOS VALORES UNAS 10 VECES MÁS ALTOS QUE LOS OBTENIDOS EN LOS TESTS DE REDUCCIÓN DE PLACA SE EXAMINÓ LA SENSIBILIDAD DE 1417 AISLADOS DE VIRUS HERPES (553 HSV-1 Y 864 HSV-2) PROCEDENTES DE UNOS 500 PACIENTES A LO LARGO DE UN PERÍODO DE 5 AÑOS. EL 90% DE LOS AISLADOS DE HSV-1FUE SENSIBLE A £0.9 MG/ML ACYCLOVIR Y EL 50% DE TODAS LAS CEPAS FUE SENSIBLE A £0.2 MG/ML DE ACICLOVIR. \r\n\r\nEN LO QUE SE REFIERE A LOS AISLADOS DE HSV-2 ISOLATES, EL 90% FUE SENSIBLE A £2.2 MG/ML Y EL 50% DE TODAS LAS CEPAS FUE SENSIBLE A £0.7 MG/ML DE ACICLOVIR. SE OBSERVARON AISLADOS CON UNA SENSIBILIDAD SIGNIFICATIVAMENTE REDUCIDA EN 44 PACIENTES. \r\n\r\nSIN EMBARGO, SE DEBE OBSERVAR QUE NI LOS PACIENTES DE ESTE ESTUDIO NI LOS AISLADOS FUERON SELECCIONADOS DE FORMA RANDOMIZADA DE MANERA QYE NO SON REPRESENTATIVOS DE LA POBLACIÓN EN GENERAL\r\n\r\nFARMACOCINÉTICA: LA FARMACOCINÉTICA DEL ACICLOVIR DESPUÉS DE SU ADMINISTRACIÓN ORAL HA SIDO EVALUADA EN 6 ESTUDIOS CLÍNICOS EN LOS QUE INTERVINIERON 110 PACIENTES ADULTOS\r\n\r\nEN UN ESTUDIO NO CONTROLADO EN 35 PACIENTES INMUNODEPRIMIDOS CON HERPES SIMPLE O INFECCIÓN POR EL VIRUS ZOSTER DE LA VARICELA, SE ADMINISTRARON CAPSULAS DE ACICLOVIR EN DOSIS DE 200 A 1000 MG CADA 4 HORAS, 6 VECES AL DÍA DURANTE 5 DÍAS. LAS CONCENTRACIONES PLASMÁTICAS AL ALCANZARSE EL \"STEADY-STATE\" (CONCENTRACIONES DE EQUILIBRIO), EL SEGUNDO DÍA FUERON DE 0.49 MG/ML DESPUÉS DE LA DOSIS DE 200 MG Y DE 2.8 MG/ML DESPUÉS DE LA DOSIS DE 800 MG.\r\n\r\nEN OTRO ESTUDIO EN 20 PACIENTES INMUNOCOMPETENTES CON INFECCIONES GENITALES RECURRENTES POR HERPES SIMPLE, SE ADMINISTRARON DOSIS DE 800 MG DE ACICLOVIR EN CÁPSULAS CADA 6 HORAS DURANTE 5 DÍAS. LAS CONCENTRACIONES EN EL STEADY STATE FUERON 1.4 MG/ML. EN GENERAL, LA FARMACOCINÉTICA DEL ACICLOVIR EN LOS NIÑOS ES SIMILAR A LA DE LOS ADULTOS. LA SEMI-VIDA DE ELIMINACIÓN DESPUÉS DE DOSIS ORALES DE 300 MG/M2 Y 600 MG/M2, EN NIÑOS DE EDADES COMPRENDIDAS ENTRE 7 MESES Y 7 AÑOS ES DE 2.6 HORASS. (INTERVALOS ENTRE 1.59 Y 3.74 HORAS). \r\n\r\nUN ESTUDIO DE BIODISPONIBILIDAD ORAL DESPUÉS DE UNA DOSIS ÚBICA MOSTRÓ QUE EL ACICLOVIR CÁPSULAS DE 200 MG ES EQUIVALENTE A 200 MG DE ACICLOVIR EN SOLUCIÓN ACUOSA. EN OTRO ESTUDIO EN 20 VOLUNTARIOS, SE COMPROBÓ QUE LA BIODISPONIBILIDAD DE LA SUSPENSIÓN DE ACICLOVIR ES LA MISMA DE LA DE LAS CÁPSULAS\r\n\r\nDESPUÉS DE LA ADMINISTRACIÓN ORAL, LA SEMI-VIDA PLASMÁTICA DEL ACICLOVIR EN VOLUNTARIOS Y EN PACIENTES CON LA FUNCIÓN RENAL NORMAL ES DE 2.5 A 3.3 HORAS. LA ELIMINACIÓN DEL FÁRMACO SIN ALTERAR SUPONE UN 14.4% (8.6% A 19.8%) DE LA DOSIS ADMINISTRADA POR VÍA ORAL. EL ÚNICO METABOLITO URINARIO (IDENTIFICADO POR CROMATOGRAFÍA LIQUIDO-LIQUIDO DE ALTA PRESIÓN) ES LA 9- [(CARBOXIMETOXI)METIL]GUANINA. LA SEMI-VIDA PLASMÁTICA Y EL ACLARAMIENTO DEL ACICLOVIR DEPENDEN DE LA FUNCIÒN RENAL, DE MODO QUE EN PACIENTES CON FUNCIÓN RENAL REDUCIDA LAS DOSIS DEBEN SER REAJUSTADAS\r\n\r\nNO SE HA ESTUDIADO LA ADMINISTRACIÓN DE ACICLOVIR EN NIÑOS DE MENOS DE 2 AÑOS.\r\n\r\nTOXICIDAD: EL ACICLOVIR ES MUY POCO TÓXICO SEGÚN SE HA PUESTO DE MANIFIESTO EN ESTUDIOS EN ANIMALES POR VARIAS VÍAS DE ADMINISTRACIÓN, INCLUYENDO LA ADMINISTRACIÓN TÓPICA EN FORMA DE UNGUENTO\r\n\r\nEN EL HOMBRE SE HAN COMUNICADO SOBREDOSIS DE HASTA 20 G (100 CÁPSULAS) SIN EFECTOS ADVERSOS INESPERADOS\r\n\r\nINDICACIONES Y POSOLOGIATRATAMIENTO DE INFECCIONES VÍRICAS DE LA PIEL Y MEMBRANAS MUCOSAS PRODUCIDAS POR EL VIRUS HERPES SIMPLE. \r\n\r\nINFECCIONES MUCOCUTÁNEAS POR VIRUS HERPES SIMPLE (VHS) EN PACIENTES INMUNODEPRIMIDOS: ES EFECTIVO EN EL TRATAMIENTO DE LA INFECCIÓN ESTABLECIDA POR VHS, DISMINUYENDO EN UN 25 A 65% EL TIEMPO DE CURACIÓN. IGUALMENTE HA DEMOSTRADO SU EFICACIA COMO PROFILAXIS DE LA INFECCIÓN POR VHS EN PACIENTES TRASPLANTADOS (MÉDULA ÓSEA, RENAL, CORAZÓN, ETC.) E INMUNODEPRIMIDOS POR HEMOPATÍAS MALIGNAS EN QUIMIOTERAPIA Y SEROPOSITIVOS PARA VHS.\r\n\r\nAUNQUE POSIBLEMENTE EFECTIVO, NO HAY EVIDENCIAS CLARAS DE UNA FAVORABLE RELACIÓN BENEFICIO-RIESGO Y COSTE-BENEFICIO EN LA PREVENCIÓN DE LA INFECCIÓN RECURRENTE POR VHS EN PACIENTES INMUNODEPRIMIDOS POR OTRAS CAUSAS: INMUNODEFICIENCIA PRIMARIA, SIDA, TUMORES SÓLIDOS, ENFERMEDADES DEL COLÁGENO, ETC. LA NECESIDAD DEL TRATAMIENTO SE ESTABLECERÁ EN BASE A LA FRECUENCIA Y GRAVEDAD DE LAS RECURRENCIAS. \r\n\r\n HERPES GENITAL: EL ACICLOVIR SE HA MOSTRADO EFICAZ EN EL TRATAMIENTO DEL PRIMER EPISODIO DE HERPES GENITAL DISMINUYENDO LA DURACIÓN DEL DOLOR Y LAS LESIONES ENTRE UN 29 Y UN 57%. EL TRATAMIENTO DEL EPISODIO INICIAL NO AFECTA LA TASA DE RECURRENCIA POSTERIOR. LA EFICACIA ES MENOR EN LOS EPISODIOS RECURRENTES DE HERPES GENITAL QUE EN EL INICIAL. ADMINISTRADO PROFILÁCTICAMENTE ES CAPAZ DE DISMINUIR LA FRECUENCIA Y SEVERIDAD DE LOS EPISODIOS DE HERPES GENITAL, SIN EMBARGO LA TASA DE RECURRENCIA VUELVE A NIVELES PREVIOS CUANDO SE SUSPENDE LA ADMINISTRACIÓN. EL MAYOR BENEFICIO DE LA PROFILAXIS CON ACICLOVIR SE HA OBSERVADO EN PACIENTES CON 6 O MÁS EPISODIOS DE HERPES GENITAL AL AÑO. \r\n\r\nDADO QUE NO SE PUEDE ASEGURAR LA SEGURIDAD DE LA ADMINISTRACIÓN DEL FÁRMACO POR PERIODOS SUPERIORES A 1 AÑO, SE RECOMIENDA SUPRIMIR LA ADMINISTRACIÓN Y OBSERVAR EL PATRÓN DE RECURRENCIAS ANTES DE DECIDIR CONTINUAR EL TRATAMIENTO POR PERIODOS MÁS PROLONGADOS. \r\n\r\n HERPES ZOSTER: EL ACICLOVIR ES EFECTIVO A LA DOSIS ESPECIFICADA EN POSOLOGÍA EN EL TRATAMIENTO DEL HERPES ZOSTER EN PACIENTES INMUNOCOMPETENTES. LA MEJORÍA ES MÁS EFECTIVA EN INFECCIONES CUTÁNEAS PROGRESIVAS O DISEMINADAS. TAMBIÉN REDUCE DISCRETAMENTE LA PROGRESIÓN DE LAS LESIONES DÉRMICAS Y EL DOLOR CON EL TRATAMIENTO DURANTE 7-10 DÍAS EN PACIENTES INMUNOCOMPETENTES CON HERPES ZOSTER. EL TRATAMIENTO DEBERÍA REALIZARSE EN LAS PRIMERAS 72 HORAS DEL CUADRO, SIENDO EL RESULTADO MEJOR CUANTO MÁS PRECOZ ES LA ADMINISTRACIÓN. SE RECOMIENDA EL TRATAMIENTO EN AQUELLOS PACIENTES DE RIESGO (DIABÉTICOS, MALNUTRIDOS, ETC.) Y/O CON HERPES ZOSTER SEVERO, SIENDO EL BENEFICIO MENOR EN EL RESTO DE PACIENTES. DIFERENTES ENSAYOS CLÍNICOS HAN DEMOSTRADO QUE EL ACICLOVIR ORAL, A LA DOSIS RECOMENDADA, PROPORCIONA UN NOTABLE BENEFICIO CLÍNICO SOBRE LA ELIMINACIÓN VIRAL, ERUPCIÓN Y DOLOR EN LA FASE AGUDA DE LA ENFERMEDAD. ALGUNOS ESTUDIOS FRENTE A PLACEBO, HAN DEMOSTRADO UNA MENOR PREVALENCIA DE NEURALGIA POSTHERPÉTICA TRAS TRATAMIENTO CON ACICLOVIR.\r\n\r\n VARICELA: EN ENSAYOS CLÍNICOS REALIZADOS EN PACIENTES INMUNOCOMPETENTES FRENTE A PLACEBO, EL ACICLOVIR HA DEMOSTRADO SER EFICAZ EN LA REDUCCIÓN DE LA EXTENSIÓN DE LA ERUPCIÓN, ASÍ COMO EN LA DISMINUCIÓN DE LA INTENSIDAD DEL PRURITO Y DE LA SINTOMATOLOGÍA GENERAL, CUANDO EL TRATAMIENTO ES INICIADO DENTRO DE LAS PRIMERAS 24 HORAS TRAS LA APARICIÓN DEL RASH CARACTERÍSTICO. NO SE HA DEMOSTRADO QUE EL TRATAMIENTO CON ACICLOVIR DISMINUYA LA INCIDENCIA DE COMPLICACIONES DERIVADAS DE LA PROPIA ENFERMEDAD.\r\n\r\nADULTOS. \r\nFUNCIÓN RENAL NORMAL: PARA EL TRATAMIENTO DE INFECCIONES PRODUCIDAS POR VIRUS HERPES SIMPLE, 2,5 ML DE SUSPENSIÓN O 1 COMPRIMIDO DE 200 MG 5 VECES AL DÍA A INTERVALOS DE APROXIMADAMENTE 4 HORAS OMITIENDO LA DOSIS NOCTURNA, DURANTE 5 DÍAS. EN PACIENTES SERIAMENTE INMUNOCOMPROMETIDOS LA DOSIS PUEDE SER DOBLADA A 400 MG 5 VECES AL DÍA. PARA LA SUPRESIÓN DE RECURRENCIAS PRODUCIDAS POR VIRUS HERPES SIMPLE EN PACIENTES INMUNOCOMPETENTES, 2,5 ML DE SUSPENSIÓN O 1 COMPRIMIDO DE 200 MG 4 VECES AL DÍA A INTERVALOS DE APROXIMADAMENTE 6 HORAS O BIEN 5 ML DE SUSPENSIÓN O 2 COMPRIMIDOS DE 200 MG 2 VECES AL DÍA, CADA 12 HORAS. EL TRATAMIENTO SERÁ INTERRUMPIDO PERIÓDICAMENTE A INTERVALOS DE 6 A 12 MESES PARA OBSERVAR POSIBLES CAMBIOS EN EL PROCESO DE LA ENFERMEDAD. PARA LA PROFILAXIS DE INFECCIONES PRODUCIDAS POR VIRUS HERPES SIMPLE EN PACIENTES INMUNOCOMPETENTES, 2,5 ML Ó 1 COMPRIMIDO DE 200 MG 4 VECES AL DÍA A INTERVALOS DE 6 HORAS. EN PACIENTES SERIAMENTE INMUNOCOMPROMETIDOS LA DOSIS PUEDE SER DOBLADA A 400 MG 4 VECES AL DÍA. PARA EL TRATAMIENTO DE INFECCIONES POR HERPES ZOSTER, 1 COMPRIMIDO DE 800 MG O 4 COMPRIMIDOS DE 200 MG O 10 ML DE SUSPENSIÓN 5 VECES AL DÍA, OMITIENDO LA DOSIS NOCTURNA, DURANTE SIETE DÍAS. EN PACIENTES SERIAMENTE INMUNOCOMPROMETIDOS (POR EJEMPLO, DESPUÉS DE UN TRANSPLANTE DE MÉDULA) Y EN AQUELLOS PACIENTES CON DIFICULTADES EN LA ABSORCIÓN INTESTINAL ES CONVENIENTE LA ADMINISTRACIÓN POR VÍA INTRAVENOSA. \r\nVARICELA: 1 COMPRIMIDO DE 800 MG O 10 ML DE SUSPENSIÓN 5 VECES AL DÍA A INTERVALOS DE 4 HORAS, OMITIENDO LA DOSIS NOCTURNA DURANTE SIETE DÍAS. \r\nFUNCIÓN RENAL ALTERADA: EN EL TRATAMIENTO DE INFECCIONES POR VIRUS HERPES SIMPLE, EN PACIENTES CON UN ACLARAMIENTO DE CREATININA IGUAL O INFERIOR A 10 ML/MINUTO, 2,5 ML DE SUSPENSIÓN O 1 COMPRIMIDO DE 200 MG CADA 12 HORAS. EN EL TRATAMIENTO DE INFECCIONES POR HERPES ZOSTER, SE RECOMIENDAN 1 COMPRIMIDO DE 800 MG O 4 COMPRIMIDOS DE 200 MG O 10 ML DE SUSPENSIÓN 2 VECES AL DÍA, PARA PACIENTES CON UN ACLARAMIENTO DE CREATININA INFERIOR A 10 ML/MIN., Y 1 COMPRIMIDO DE 800 MG O 4 COMPRIMIDOS DE 200 MG O 10 ML DE SUSPENSIÓN 3 Ó 4 VECES AL DÍA A INTERVALOS DE 6-8 HORAS, PARA PACIENTES CON UN ACLARAMIENTO DE CREATININA DE 10-25 ML/MINUTO. \r\nVARICELA: SE RECOMIENDA 1 COMPRIMIDO DE 800 MG O 10 ML DE SUSPENSIÓN 2 VECES AL DÍA, PARA PACIENTES CON UN ACLARAMIENTO DE CREATININA INFERIOR A 10 ML/MIN., Y 1 COMPRIMIDO DE 800 MG O 10 ML DE SUSPENSIÓN 3 Ó 4 VECES AL DÍA A INTERVALOS DE 6 A 8 HORAS, PARA PACIENTES CON UN ACLARAMIENTO DE CREATININA DE 10-25 ML/MIN. EN PERSONAS DE EDAD SE RECOMIENDA UN APORTE DE LÍQUIDO ADECUADO MIENTRAS ESTÉN SOMETIDAS A ALTAS DOSIS DE ZOVIRAX POR VÍA ORAL. EN AQUELLOS PACIENTES ANCIANOS CON UNA FUNCIÓN RENAL ALTERADA SE ADMINISTRARÁ UNA DOSIS REDUCIDA. \r\nNIÑOS. \r\nVARICELA: NIÑOS MAYORES DE 6 AÑOS: 10 ML DE SUSPENSIÓN O 1 COMPRIMIDO DE 800 MG DE ACICLOVIR, CUATRO VECES AL DÍA DURANTE CINCO DÍAS. NIÑOS ENTRE 2 Y 6 AÑOS: 5 ML CUATRO VECES AL DÍA DURANTE CINCO DÍAS. NIÑOS MENORES DE 2 AÑOS: 2,5 ML CUATRO VECES AL DÍA DURANTE CINCO DÍAS. LA POSOLOGÍA PUEDE CALCULARSE CON MÁS EXACTITUD COMO 20 MG/KG DE PESO CORPORAL (SIN SOBREPASAR LOS 800 MG) CUATRO VECES AL DÍA. \r\nPARA EL TRATAMIENTO DE INFECCIONES POR VIRUS HERPES SIMPLE Y PROFILAXIS EN NIÑOS INMUNOCOMPROMETIDOS: LOS NIÑOS MAYORES DE 2 AÑOS SERÁN TRATADOS CON DOSIS DE ADULTOS Y LOS NIÑOS MENORES DE 2 AÑOS SERÁN TRATADOS CON LA MITAD DE LA DOSIS DE ADULTOS.\r\n\r\nCONTRAINDICACIONES Y ADVERTENCIAS\r\n\r\nEL ACICLOVIR ESTÁ CONTRAINDICADO EN PACIENTES CON HIPERSENSIBILIDAD AL FÁRMACO.\r\n\r\nEN PACIENTES CON ALTERACIÓN DE LA FUNCIÓN RENAL SE REDUCIRÁ LA DOSIS DIARIA. SE DEBEN EVITAR LAS RELACIONES SEXUALES DE PACIENTES DE HERPES GENITAL CON LESIONES VISIBLES, YA QUE EXISTE EL RIESGO DE TRANSMITIR LA INFECCIÓN A LA PAREJA.\r\n  \r\n EL ACICLOVIR SE CLASIFICA DENTRO DE LA CATEGORÍA C DE RIESGO EN EL EMBARAZO. SÓLO SE UTILIZARÁ EN AQUELLOS CASOS EN LOS QUE PREVIAMENTE LA VALORACIÓN RIESGO-BENEFICIO DE SU APLICACIÓN ACONSEJE SU UTILIZACIÓN. ESTUDIOS REALIZADOS EN HUMANOS MUESTRAN QUE DESPUÉS DE LA ADMINISTRACIÓN, ACICLOVIR PUEDE APARECER EN LA LECHE MATERNA.\r\n    \r\n  INTERACCIONES CON OTROS MEDICAMENTOS\r\n\r\nLA ADMINISTRACIÓN SIMULTÁNEA CON PROBENECID AUMENTA LA VIDA MEDIA DEL ACICLOVIR Y EL ÁREA BAJO LA CURVA DE SUS CONCENTRACIONES PLASMÁTICAS. LOS MEDICAMENTOS QUE ALTERAN LA FISIOLOGÍA RENAL PODRÍAN INFLUENCIAR LA FARMACOCINÉTICA DEL ACICLOVIR. \r\n\r\nSE HA COMUNICADO QUE LA ADMINISTRACIÓN DE ACICLOVIR A PACIENTES BAJO UN REGIMEN DE FENITOÍNA Y VALPROATO OCASIONÓ UNA REDUCCIÓN SIGNIFICATIVA DE LAS CONCENTRACIONES SÉRICAS DE FENITOÍNA CON PÉRDIDA DEL CONTROL SOBRE LAS CONVULSIONES. FUERON NECESARIAS AJUSTES DE LAS DOSIS DE FENITOÍNA CUANDO EL ACICLOVIR FUÉ AÑADIDO Y DISCONTINUADO. EL ACICLOVIR NO PARECE AFECTAR LAS CONCENTRACIONES DE VALPROATO. HASTA QUE HAYA MÁS DATOS, EL MÉDICO DEBE ESTAR PREPARADO PARA HACER LOS AJUSTES NECESARIOS DE LAS DOSIS DE ESTOS ANTICONVULSIVANTES SI SE INICIA O DISCONTINUA UN TRATAMIENTO CON ACICLOVIR.\r\n\r\nLA COADMINISTRACIÓN DE MICOFENOLATO Y DE ACICLOVIR A VOLUNTARIOS SANOS INDUJO CAMBIOS IGNIFICATIVOS DE LAS CONCENTRACIONES PLASMÁTICAS DE ÁCIDO MICOFENÓLICO. SIN EMBARGO, LOS METABOLITOS GLUCURÓNIDOS DE ACICLOVIR Y DE MICOFENOLATO AUMENTARON EN UN 10.6% Y 21.9%, RESPECTIVAMENTE. DADO QUE LAS CONCENTRACIONES DE AMBOS FÁRMACOS ESTÁN AUMENTADAS EN PRESENCIA DE INSUFICIENCIA RENAL, PUEDE HABER UNA COMPETENCIA PARA LA ELIMINACIÓN TUBULAR, CON UN INCREMENTO ADICIONAL DE LAS CONCENTRACIONES DE AMBOS FÁRMACOS\r\n\r\nEL ACICLOVIR AUMENTA LA ACTIVIDAD IN VITRO DE LA ZIDOVUDINA, ZDV Y HA SIDO ADMINISTRADO CONCOMITANTEMENTE PARA INTENTAR AUMENTAR LA EFICACIA DE LA ZIDOVUDINA FRENTE AL HIV. LA ASOCIACIÓN NO PRODUJO NINGÚN BENEFICIO SIGNIFICATIVO Y ESTUVO ACOMPAÑADA POR SOMNOLENCIA Y LETARGIA EN ALGUNOS PACIENTES.\r\n\r\nREACCIONES ADVERSAS\r\n\r\nSE HAN DESCRITO CASOS DE ERUPCIONES CUTÁNEAS; ÉSTAS DESAPARECIERON CON LA INTERRUPCIÓN DEL TRATAMIENTO. SE HAN DESCRITO OTROS CASOS EXTREMADAMENTE RAROS DE LIGERAS ELEVACIONES TRANSITORIAS DE BILIRRUBINA Y ENZIMAS HEPÁTICAS, LIGERAS DISMINUCIONES EN LOS ÍNDICES HEMATOLÓGICOS, DOLOR DE CABEZA, FATIGA, Y REACCIONES NEUROLÓGICAS LEVES Y REVERSIBLES. SE HAN DESCRITO TAMBIÉN ALTERACIONES GASTROINTESTINALES COMO NÁUSEAS, VÓMITOS, DIARREAS Y DOLORES ABDOMINALES.\r\n\r\nSOBREDOSIFICACIÓN: ES POCO PROBABLE LA APARICIÓN DE EFECTOS TÓXICOS GRAVES. PUEDE OCURRIR LA PRECIPITACIÓN DEL ACICLOVIR EN LOS TÚBULOS RENALES CUANDO SE EXCEDE EL LÍMITE DE SOLUBILIDAD (2.5 MG/ML). SE HAN OBSERVADO LESIONES RENALES RELACIONADAS CON LA ADMINISTRACIÓN DE ACICLOVIR EN LAS SIGUIENTES ESPECIES: RATAS TRATADAS CON DOSIS IV E IP DE 20 MG/KG/DÍA DURANTE 21 Y 31 DIAS, RESPECTIVAMENTE Y CON DOSIS SUBCUTÁNEAS DE 100 MG/KG/DÍA DURANTE 10 DIAS; EN EL CONEJO CON DOSIS SC E IV DE 50 MG/KG/DÍA DURANTE 13 DIAS Y EN PERROS CON DOSIS IV DE 100 MG/KG/DIA DURANTE 31 DIAS. EN TODOS LOS CASOS LAS LESIONES SE DEBEN A LA CRISTALIZACIÓN Y OBSTRUCCIÓN DE LOS TÚBULOS RENALES.\r\n\r\nLA HEMODIÁLISIS OCASIONA UNA REDUCCIÓN DEL 60% EN LAS CONCENTRACIONES PLASMÁTICAS DE ACICLOVIR.\r\n \r\n\r\n \r\n PRESENTACION\r\n\r\nACICLOSTAD COMPRIMIDOS DE 200, 800 MG Y CREMA 5% \r\nACICLOVIR BAYVIT EFG COMPRIMIDOS DE 200, 800 MG \r\nACICLOVIR CENTRUM EFG COMPRIMIDOS DE 200, 800 MG Y CREMA 5% \r\nACICLOVIR MABO EFG COMPRIMIDOS DE 200, 800 MG Y CREMA 5% \r\nACICLOVIR MUNDOGEN FARMA EFG COMPRIMIDOS DE 200, 800 MG \r\nMAYNAR COMPRIMIDOS DE 200, 800 MGCY CREMA 5 % \r\nVIRHERPES SUSPENSION 400 MG/5 ML, COMPRIMIDOS DE 200, 800 MG Y CREMA 5%. VIAL LIOF. 250 MG IV \r\nVIRMEN COMPRIMIDOS DE 200, 800 MG, CREMA 5% Y POMADA OFTÁLMICA 3% \r\nZOVIRAX COMPRIMIDOS DE 200, 800 MG, CREMA AL 5 %, POMADA OFTÁLMICA 3 %, SUSPENSIÓN. 400 MG/5 ML',NULL,1,'Joel-PC','jmedrano',NULL,NULL,'2022-10-31','2022-10-31 00:12:17');

/*Table structure for table `therapies` */

DROP TABLE IF EXISTS `therapies`;

CREATE TABLE `therapies` (
  `id_therapy` int(11) NOT NULL AUTO_INCREMENT,
  `code_therapy` varchar(250) DEFAULT NULL,
  `name_therapy` varchar(250) DEFAULT NULL,
  `state_therapy` int(11) DEFAULT 1,
  `pcreg_therapy` varchar(250) DEFAULT NULL,
  `usreg_therapy` varchar(250) DEFAULT NULL,
  `pcmod_therapy` varchar(250) DEFAULT NULL,
  `usmod_therapy` varchar(250) DEFAULT NULL,
  `date_created_therapy` date DEFAULT NULL,
  `date_updated_therapy` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id_therapy`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

/*Data for the table `therapies` */

insert  into `therapies`(`id_therapy`,`code_therapy`,`name_therapy`,`state_therapy`,`pcreg_therapy`,`usreg_therapy`,`pcmod_therapy`,`usmod_therapy`,`date_created_therapy`,`date_updated_therapy`) values (1,'0001','ACARICIDA, PEDICULICIDA',1,NULL,NULL,NULL,NULL,'2022-10-30','2022-10-30 20:55:16'),(2,'0002','AMEBICIDA GIARDICIDA TRICOMONICIDA',1,'Joel-PC','jmedrano','Joel-PC','jmedrano','2022-10-30','2022-10-30 22:43:05');

/*Table structure for table `users` */

DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
  `id_user` int(11) NOT NULL AUTO_INCREMENT,
  `rol_user` varchar(20) DEFAULT NULL,
  `picture_user` varchar(250) DEFAULT NULL,
  `displayname_user` varchar(250) DEFAULT NULL,
  `username_user` varchar(250) DEFAULT NULL,
  `password_user` varchar(250) DEFAULT NULL,
  `email_user` varchar(250) DEFAULT NULL,
  `phone_user` varchar(250) DEFAULT NULL,
  `address_user` varchar(250) DEFAULT NULL,
  `country_user` varchar(250) DEFAULT NULL,
  `city_user` varchar(250) DEFAULT NULL,
  `state_user` int(11) DEFAULT 1,
  `id_company_user` int(11) DEFAULT NULL,
  `last_login_user` datetime DEFAULT NULL,
  `pcreg_user` varchar(250) DEFAULT NULL,
  `usreg_user` varchar(250) DEFAULT NULL,
  `pcmod_user` varchar(250) DEFAULT NULL,
  `usmod_user` varchar(250) DEFAULT NULL,
  `token_user` text DEFAULT NULL,
  `token_exp_user` text DEFAULT NULL,
  `verification_user` int(11) NOT NULL DEFAULT 0,
  `date_created_user` date DEFAULT NULL,
  `date_updated_user` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id_user`)
) ENGINE=InnoDB AUTO_INCREMENT=69 DEFAULT CHARSET=utf8;

/*Data for the table `users` */

insert  into `users`(`id_user`,`rol_user`,`picture_user`,`displayname_user`,`username_user`,`password_user`,`email_user`,`phone_user`,`address_user`,`country_user`,`city_user`,`state_user`,`id_company_user`,`last_login_user`,`pcreg_user`,`usreg_user`,`pcmod_user`,`usmod_user`,`token_user`,`token_exp_user`,`verification_user`,`date_created_user`,`date_updated_user`) values (1,'administrador','joel.jpg','Joel Medrano','jmedrano','$2a$07$azybxcags23425sdg23sdeanQZqjaf6Birm2NvcYTNtJw24CsO5uq','jvmedranog@gmail.com',NULL,NULL,NULL,NULL,1,2,NULL,NULL,NULL,NULL,NULL,'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NjcxNzc1ODQsImV4cCI6MTY2NzI2Mzk4NCwiZGF0YSI6eyJpZCI6IjEiLCJlbWFpbCI6Imp2bWVkcmFub2dAZ21haWwuY29tIn19.KiRzYC4nL07BDRIeJlJLNzVKiTuaDO13_EDrF1Jc0aI','1667263984',0,'2022-10-25','2022-10-30 19:53:04'),(2,'administrador',NULL,'Tiffany Cunza','tcunza','$2a$07$azybxcags23425sdg23sdeanQZqjaf6Birm2NvcYTNtJw24CsO5uq','cunza.dg@gmail.com',NULL,NULL,NULL,NULL,0,3,NULL,NULL,NULL,NULL,NULL,'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NjY3NDk0MzcsImV4cCI6MTY2NjgzNTgzNywiZGF0YSI6eyJpZCI6IjMxIiwiZW1haWwiOiJjdW56YS5kZ0BnbWFpbC5jb20ifX0.SuXAap6ZT-FlZFUMSI9YeOjrScual8MLS8IGprJzspM','1666835837',0,'2022-10-25','2022-10-28 20:43:05'),(3,'vendedor',NULL,'Juan Carlos Arcila Díaz',NULL,'','jdelaarcila@correo.com',NULL,NULL,NULL,NULL,1,1,NULL,NULL,NULL,NULL,NULL,'','',0,'2022-10-24','2022-10-28 20:43:01'),(4,'vendedor',NULL,'Jorge García',NULL,'','jgarcia@correo.com',NULL,NULL,NULL,NULL,1,3,NULL,NULL,NULL,NULL,NULL,'','',0,'2022-10-24','2022-10-28 20:43:00'),(5,'vendedor',NULL,'Javier Arturo Vázquez Olivares',NULL,'','jdelavazquez@correo.com',NULL,NULL,NULL,NULL,1,2,NULL,NULL,NULL,NULL,NULL,'','',0,'2022-10-24','2022-10-28 20:43:00'),(6,'vendedor',NULL,'Rodrigo Martinez Blanco',NULL,'','rblanco@correo.com',NULL,NULL,NULL,NULL,0,2,NULL,NULL,NULL,NULL,NULL,'','',0,'2022-10-24','2022-10-29 23:59:43'),(7,'vendedor',NULL,'Ángel Arias',NULL,'','aarias@correo.com',NULL,NULL,NULL,NULL,1,1,NULL,NULL,NULL,NULL,NULL,'','',0,'2022-09-29','2022-10-28 20:42:48'),(8,'vendedor',NULL,'Aldo Olivares',NULL,'','aolivares@correo.com',NULL,NULL,NULL,NULL,1,1,NULL,NULL,NULL,NULL,NULL,'','',0,'2022-09-29','2022-10-28 20:42:48'),(9,'vendedor','9.png','Redait Media','rmedia','','rmedia@correo.com',NULL,NULL,NULL,NULL,1,3,NULL,NULL,NULL,'Joel-PC','jmedrano','','',0,'2022-09-29','2022-10-28 20:35:39'),(67,'administrador','67.png','Carlos Medrano Guere','cmedrano','$2a$07$azybxcags23425sdg23sdeanQZqjaf6Birm2NvcYTNtJw24CsO5uq','cmedrano@gmail.com',NULL,NULL,NULL,NULL,1,2,NULL,'Joel-PC','jmedrano',NULL,NULL,NULL,NULL,0,'2022-10-27','2022-10-28 20:43:10'),(68,'vendedor','68.png','Carla Guerrero','cguerrero','$2a$07$azybxcags23425sdg23sdeanQZqjaf6Birm2NvcYTNtJw24CsO5uq','cguerrero@gmail.com',NULL,NULL,NULL,NULL,0,1,NULL,'Joel-PC','jmedrano','Joel-PC','jmedrano','eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NjcwMTE1NzcsImV4cCI6MTY2NzA5Nzk3NywiZGF0YSI6eyJpZCI6IjY4IiwiZW1haWwiOiJjZ3VlcnJlcm9AZ21haWwuY29tIn19.GAjoC2XDchCUkp3zWGXFyrw5qZ-gXq-1CedJvAGtyXg','1667097977',0,'2022-10-27','2022-10-28 21:46:17');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
